;;; cql-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cql-mode.el

(autoload 'cql-mode "cql-mode" "\
cql major mode

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.cql\\'" . cql-mode))
(register-definition-prefixes "cql-mode" '("cql-mode-font-lock-keywords"))

;;; End of scraped data

(provide 'cql-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cql-mode-autoloads.el ends here
